version: "3.9"

services:
    product_service_db:
        container_name: product_service_db
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_DB: product_service
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
        networks:
            product_service_network:

    product_service:
        build: product_service
        image: onlineshop/product_service:latest
        restart: always
        environment:
            spring.datasource.url: jdbc:postgresql://product_service_db/product_service
            spring.datasource.username: root
            spring.datasource.password: root
            spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQL95Dialect
            spring.datasource.driver-class-name: org.postgresql.Driver
        ports:
           - 9000:8080
        depends_on:
            - postgresdb
        networks:
            product_service_network:

    customer_service_db:
        container_name: customer_service_db
        image: postgres:11.4
        restart: always
        environment:
            POSTGRES_DB: customer_service
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
        networks:
            customer_service_network:

    customer_service:
        build: customer_service
        restart: on-failure
        environment:
            spring.datasource.url: jdbc:postgresql://customer_service_db/customer_service
            spring.datasource.username: root
            spring.datasource.password: root
            spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQL95Dialect
            spring.datasource.driver-class-name: org.postgresql.Driver
        ports:
            - 9001:8080
        depends_on:
            - customer_service_db
        networks:
            customer_service_network:

networks:
    product_service_network:
        driver: bridge
    customer_service_network:
        driver: bridge
