version: "3.9"

services:
    grafana_monitoring:
         container_name: onlineshop_grafana_monitor
         image: grafana/grafana-enterprise
         restart: always
         ports:
            - 3000:3000
         networks:
            onlineshop_network:
 
    prometheus_gatherer:
        container_name: onlineshop_prometheus_gatherer
        image: prom/prometheus:latest
        restart: always
        ports:
            - 9090:9090
        depends_on: 
            - cadvisor
            - product_service
        networks:
            onlineshop_network:

    cadvisor:
        container_name: cadvisor
        image: gcr.io/cadvisor/cadvisor:latest
        ports: 
            - 9091:8080
        depends_on:
            - product_service
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:rw
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
        networks:
            onlineshop_network:
                    
    product_service_db:
        container_name: product_service_db
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_DB: product_service
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
        networks:
            onlineshop_network:

    product_service:
        build: product_service
        image: onlineshop/product_service:latest
        restart: always
        environment:
            spring.datasource.url: jdbc:postgresql://product_service_db/product_service
            spring.datasource.username: root
            spring.datasource.password: root
            spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQL95Dialect
            spring.datasource.driver-class-name: org.postgresql.Driver
        ports:
            - 9000:8080
        depends_on:
            - product_service_db
        networks:
            onlineshop_network:

    customer_service_db:
        container_name: customer_service_db
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_DB: customer_service
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
        networks:
            onlineshop_network:

    customer_service:
        build: customer_service
        restart: always
        environment:
            spring.datasource.url: jdbc:postgresql://customer_service_db/customer_service
            spring.datasource.username: root
            spring.datasource.password: root
            spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQL95Dialect
            spring.datasource.driver-class-name: org.postgresql.Driver
        ports:
            - 9001:8080
        depends_on:
            - customer_service_db
        networks:
            onlineshop_network:

networks:
    onlineshop_network:
        driver: bridge
