version: "3.9"

services:
    product-service-db:
        container_name: product-service-db
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_DB: product_service
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
        networks:
            onlineshop_network:

    product-service:
        build: product-service
        image: onlineshop/product_service:latest
        restart: always
        environment:
            spring.datasource.url: jdbc:postgresql://product-service-db/product_service
            spring.datasource.username: root
            spring.datasource.password: root
            spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQL95Dialect
            spring.datasource.driver-class-name: org.postgresql.Driver
            EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service:8761/eureka
        ports:
            - 9000:8080
        depends_on:
            - product_service_db
            - eureka_service
        networks:
            onlineshop_network:

    customer-service-db:
        container_name: customer-service-db
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_DB: customer_service
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
        networks:
            onlineshop_network:

    customer-service:
        build: customer-service
        restart: always
        environment:
            spring.datasource.url: jdbc:postgresql://customer-service-db/customer_service
            spring.datasource.username: root
            spring.datasource.password: root
            spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQL95Dialect
            spring.datasource.driver-class-name: org.postgresql.Driver
        ports:
            - 9001:8080
        depends_on:
            - customer_service_db
            - eureka_service
        networks:
            onlineshop_network:

    eureka-service:
        build: eureka_service
        image: onlineshop/eureka-service:latest
        restart: always
        ports:
            - 8761:8761
        networks:
            onlineshop_network:

networks:
    onlineshop_network:
        driver: bridge
