version: '3'
#start with: docker compose --profile dev up -d --build
services:
    # ORDER SERVICE
    customer_service:
        build: .
        restart: on-failure
        ports:
            - 8080:8080
        depends_on:
            - database

    # DATABASE
    database:
        container_name: postgres_db
        image: 'postgres:11.4'
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_DB: order_service_db
            POSTGRES_USER: user
            POSTGRES_PASSWORD: abc
