version: "3.9"

services:
    postgresdb:
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: product_service
        ports:
           - "5432:5432"
        networks:
            servicenetwork:

    product_service:
        build: .
        image: onlineshop/product_service:latest
        restart: always
        environment:
            spring.datasource.url: jdbc:postgresql://postgresdb:5432/product_service
            spring.datasource.username: root
            spring.datasource.password: root
            spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQL95Dialect
            spring.datasource.driver-class-name: org.postgresql.Driver
        ports:
           - "8080:8080"
        depends_on:
            - postgresdb
        networks:
            servicenetwork:
networks:
    servicenetwork:
        driver: bridge
